const groceryItems = [
  { name: 'Apple', price: '$1.25' },
  { name: 'Orange', price: '$1.25' },
  { name: 'Kiwi', price: '$1.25' },
  { name: 'Pear', price: '$1.25' },
  { name: 'Peach', price: '$1.25' },
  { name: 'Banana', price: '$1.25' },
  { name: 'Strawberry', price: '$3' },
  { name: 'Grape', price: '$3' },
  { name: 'Cherry', price: '$3' },
  { name: 'Durian', price: '$1.50' },
  { name: 'Cranberry', price: '$2' },
  { name: 'Blueberry', price: '$3' },
  { name: 'Watermelon', price: '$5' },
  { name: 'Pineapple', price: '$5' },
  { name: 'Mango', price: '$2.50' },
  { name: 'Lemon', price: '$1.75' },
  { name: 'Lime', price: '$1.75' },
  { name: 'Blackberry', price: '$3' },
  { name: 'Citrus', price: '$3' },
  { name: 'Grapefruit', price: '$4' },
  { name: 'Pork', price: '$5' },
  { name: 'Chicken drumstick', price: '$5' },
  { name: 'Chicken wing', price: '$5' },
  { name: 'Beef', price: '$5' },
  { name: 'Turkey', price: '$5' },
  { name: 'Duck', price: '$5' },
  { name: 'Sausage', price: '$5' },
  { name: 'Salmon', price: '$6' },
  { name: 'Goose', price: '$5' },
  { name: 'Crab', price: '$7' },
  { name: 'Lobster', price: '$7' },
  { name: 'Lamb', price: '$6' },
  { name: 'Steak', price: '$6' },
]
//need to add image category. might delete some items if no time
